### ISSUE TITLE
create 4th tab with unmappable items

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/place-identificator#15]
And refactor the queries that fill those tabs

**Comment by mmmenno** [comment]
Tab is er, maar wat tonen we daar? Misschien toch nog het invoerveld als op 'geen resultaten'? Je moet het bij eventueel toch achterhalen wel weg kunnen krijgen bij 'niet te achterhalen'!

**Comment by mmmenno** [comment]
Je kan er nu alsnog een URI invoeren
