### ISSUE TITLE
Als je aangeeft dat je je eigen id mee terug wilt, dan gebeurt dat niet!

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#34]

**Comment by KitsR** [comment]
Heb het getest, maar bij mij geeft hij eigen ID in de CSV-download nog niet terug...

**Comment by phpetra** [comment]
Heb je alle stappen opnieuw doorlopen?

**Comment by KitsR** [comment]
Ja, van upload tot download.

**Comment by KitsR** [comment]
Doe nog een test met ander test-bestand, moment.

**Comment by phpetra** [comment]
Bij mij lukt het wel.... met welke set doe je dit?

**Comment by KitsR** [comment]
Check, hij doet het nu wel goed!

Het werkt niet met het bestand dat ik afgelopen maandag al heb geüpload:
https://github.com/erfgoed-en-locatie/historische-geocoder/blob/gh-pages/testdata/confessieboeken/confessieboeken-rand-100-enkeltjes-2.csv

Het werkt nu wel met een bestand dat ik nog niet eerder heb geüpload:
https://github.com/erfgoed-en-locatie/historische-geocoder/blob/gh-pages/testdata/voc-opvarenden/random-100-kolomnamen-2.csv

Na dat succes heb ik nogmaals gehele traject geprobeerd met nieuwe upload van het eerste bestand, maar download geeft opnieuw geen eigen ID mee.

Misschien dat de tool intern een al eerder geüploade bestand hergebruikt, bij het nogmaals uploaden van hetezlfde bestand?

**Comment by phpetra** [comment]
Ik ben het op het spoor: het werkt met alle velden behalve als je het eerste veld kiest.... moment, fix komt eraan.

**Comment by phpetra** [comment]
@RalphKits Nu doet ie ze allemaal.

**Comment by KitsR** [comment]
Signed, sealed, delivered! Of beter nog: Tested, checked, succeeded!

:)

**Comment by phpetra** [comment]
Mooi :-)
