### ISSUE TITLE
scherm met 4 opties voor fuzzy, exact, exacter en literal zoeken, als voorbeeld tonen

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/place-identificator#45]
Inzichtelijk maken hoe de opties werken, en wat het verschil is tussen 

"Den Bos" &exact=false
"Den Bos" &exact=true
Den Bos &exact=true
Den Bos &exact=false

Of misschien een pagina met precies dit voorbeeld als uitleg en een vrij in te voeren veldje, dat gaat zoeken

**Comment by jobspierings** [comment]
tzt uitleggen op erfeo.nl
