### ISSUE TITLE
scherm multiple treffers toont soms maar 1 treffer, terwijl er meer zijn

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/place-identificator#46]
En dat komt dan doordat nu alleen treffers getoond worden met een geometrie die uit tgn, geonames, bag of gemeentegeschiedenis komt en niet bijvoorbeeld uit dbpedia....
DBpedia concepten hebben namelijk WEL geometrieen maar nauwelijks links naar andere pits

**Comment by jobspierings** [comment]
fixed.
