### ISSUE TITLE
straatnamen standaardiseren toevoegen

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/place-identificator#47]
Op verzoek van Niene:
- straatnamen kunnen standaardiseren en een nationaal-wegenbestand uri terugleveren

Workflow:
- [x] nwb veld toeveogen aan db
- [x] hg:Street optie toevoegen aan stanaardiseer keuze-veld
- [x] indien gekozen, extra veldje tonen waarin een hg:uri ingevoerd kan worden van de plaats/gemeente of ander gebied waarin je wil zoeken
- [x] verwerking van response uitbreiden met Streets
- [x] interfaces aanpassen en uitbreiden met nwb details indien gevonden

**Comment by jobspierings** [comment]
Petra loopt na en test.
