### ISSUE TITLE
TGN kolommetje toont alt-names

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#56]
Zie afbeelding 

![image](https://cloud.githubusercontent.com/assets/4539618/8276895/4c551ff6-18bc-11e5-8c25-327d9eb3a48c.png)

**Comment by mmmenno** [comment]
Dit komt waarschijnlijk doordat alternatieve termen ook in de dataset `tgn` zijn opgenomen, met als id bijv. `tgn/term-1001180562` (dat is Leythen). Het script pakt dan gewoon de eerste naam die het tegenkomt.

Oplossing binnen deze applicatie zou zijn: pak de eerste naam **met geometrie**.

**Comment by phpetra** [comment]
Nu opgelost!
