### ISSUE TITLE
Grote bestanden worden niet of half gestandaardiseerd

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#57]
Test met VOC opvarenden toont dat:
- 140.000+ (de hele set) helemaal geen resultaat geeft
- 70000 ook niet
- 20000 stopt na 2350 resultaten
- 5000 geeft van elk record een resultaat

**Comment by mmmenno** [comment]
Volgens @phpetra komt dit doordat een set in z'n geheel door php in het geheugen wordt genomen en daarna pas resultaten in de db worden weggeschreven. Dit zou opgesplitst moeten worden in batches.

**Comment by phpetra** [comment]
Optimalisatie is inmiddels gedaan.
