### ISSUE TITLE
Items get standardized to '', should be categorized as 'geen resultaat'

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#58]
Sometimes, a place gets standardized to, well, nothing.

![image](https://cloud.githubusercontent.com/assets/4539618/8278020/65f5e16e-18c8-11e5-9d8a-d7dfd527c4b4.png)

This happens when one result is found and this one _klont_ does not contain a tgn or geonames or gemeentegeschiedenis pit. Kloeke places in Belgium and France do tend to cause this problem.

Solution: check for tgn, geonames or gg pit, set to 'no result' if not found.

**Comment by phpetra** [comment]
WIll not happen anymore in the new branch.
