### ISSUE TITLE
On 'meerdere resultaten', map shows fewer results than are mentioned in 'aantal hits' column

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#59]
This seems to happen when multiple results are found, but not all results contain tgn, geonames or gg pits (only these are shown on the map, because these are the ones you want to standardize to).

'Almkerk' for instance gets two hits, but there's only one Almkerk known by tgn geonames & gg. The other hit is an Almkerk from the `verdwenen-dorpen` dataset.

This is fundamental: if you want to standardize to tgn geonames or gg only, you should only check for places within these datasets. This should probably be done within the application after getting api results. 

Asking the api only for pits within certain datasets is nice, but wouldn't work here, because all toponyms from other datasets, even if related to tgn etc, would probably not be found as well.

Related to #58

**Comment by phpetra** [comment]
Integrated in version2 branch
