### ISSUE TITLE
Bevindingen Inge

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/place-identificator#61]
Dag Monika en Ralph,

Ik ben nog even met mijn datasets aan de slag gegaan. Mijn bevindingen hieronder.

Eerste dataset – volledige thesaurus

Er worden 832 termen gestandaardiseerd, 1078 hebben meerdere resultaten en 13584 hebben geen resultaten. Het grote deel zonder resultaat is verklaarbaar door de wereldwijde scope van onze thesaurus.

Om deze matches verder te evalueren zou ik ze willen exporteren. Ik krijg echter dezelfde foutmelding als tijdens de workshop:

“Notice: Undefined index: gg-geometry in /var/www/www-root/locatienaaruri/src/Pid/Mapper/Provider/DataSetControllerProvider.php on line 390
We are sorry, but something went terribly wrong.”

Ik heb daarom de gemeentegeschiedenis uitgezet; de export werkte toen wel. Vandaag wilde ik een andere set exporteren: hierbij hetzelfde probleem, maar dit keer wilde de TGN-data niet meewerken en kon ik dus alleen de Geonames-set exporteren.

Tweede dataset – Broader term = “Nederland”

De totale dataset bestaat uit 4046 termen. Na uploaden zijn hiervan plusminus 600 termen behandeld. Dit is ook het geval bij een tweede keer uploaden van dezelfde set. Ik ben vervolgens eerst langs de Gestandaardiseerde termen gelopen, vervolgens langs de Meerdere resultaten en als laatste door de Geen resultaten. Wat me hierbij opviel:
- Ik zou graag willen dat een term gemarkeerd kan worden als ik hem gecontroleerd heb, zodat ik weet wat ik gezien heb.
- De knop ‘niet te achterhalen’ lijkt niet te werken, maar na aanklikken van het volgende record blijkt de voorgaande term toch weggeschreven te zijn.
- Bij Gestandaardiseerd: sommige plaatsen zijn niet goed gekoppeld maar ook niet ‘niet te achterhalen’- de goede match staat niet in de gegeven lijst. Ik zou dus ook daar graag zelf een URI kunnen invoeren/aanpassen.
- De kaartoptie bij meerdere termen is handig. Maar, als er een omtrek aangegeven is en daar ook nog een ander vlaggetje in staat, kan dat vlaggetje niet aangeklikt worden.
- Bij het invullen van URI's bij Geen Resultaten staat de URI soms opeens ingevuld bij een term verderop in de lijst.  
- Voor sommige termen kan maar geen URI opgeslagen worden. Melding: "Er ging iets fout met een verbinding. Probeer het later nog eens. ". Een andere term direct daarna opslaan werkt wel. Dit lijkt gerelateerd te zijn aan gebieden met een TGN:1-nummer ipv een TGN:7-nummer. (bij rivieren, zee, dijken). Maar niet alleen, deze wil ook niet: http://vocab.getty.edu/tgn/7032127
- Ik heb termen van 'geen resultaten' URI's gegeven, waardoor de gestandaardiseerde termen opgelopen waren naar 232. Toen ik klaar was, klikte ik op 'gestandaardiseerd' en toen sprong de teller weer terug naar 168.

Deze dataset heb ik geëxporteerd – alleen de Geonamesinfo lukte. Er bleven 99 termen over waar de coördinaten voor beschikbaar waren. Dit is wat mij betreft een beetje een teleurstellend resultaat – in dezelfde tijd had ik deze termen met de hand van coördinaten kunnen voorzien. Voor mij is het nu belangrijk om een export kunnen maken van de TGN-gegevens en natuurlijk het verwerken van de hele dataset in plaats van een deel daarvan.

---

**Comment by phpetra** [comment]
Eén ding kan ik wel al verklaren: waarom het niet lukt om die TGN-gebieden op te slaan: deze applicatie is (vooralsnog) bedoeld voor het standaardiseren van plaatsen of gemeentes.... niet voor gebieden. Op het moment dat je een willekeurige TGN uri invoert, doet het systeem een call naar TGN om aanvullende gegevens (met name de geometrie) op te halen. Als die geometrie ontbreekt, wordt het resultaat genegeerd.
Je kunt het verschil zien met bijvoorbeeld: http://vocab.getty.edu/tgn/7003616 (klik bij beide eens op de waarde achter foaf:focus (helemaal onderaan).

**Comment by wires** [comment]
Mooie feedback dit! (even wat leesbaarder gemaakt)

**Comment by phpetra** [comment]
Punten zijn met de rewrite verholpen. Tijd voor nieuwe testronde.
