### ISSUE TITLE
Items on 'meerdere resultaten' have only one result

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#64]
According to standaardiseertool two items in my test got muliple results:

![image](https://cloud.githubusercontent.com/assets/4539618/10782761/2a38eba4-7d53-11e5-986d-3b27d891efd5.png)

But when you go to 'bewerk' both only show one result:

![image](https://cloud.githubusercontent.com/assets/4539618/10782801/7eb05140-7d53-11e5-84ab-ffa3fd6e3d85.png)

Also, the api gives just one feature on [https://api.histograph.io/search?q=Arnhem&exact=true&type=hg:Place&geometry=false](https://api.histograph.io/search?q=Arnhem&exact=true&type=hg:Place&geometry=false) .

Can it be that the initial standardization doesn't ask api for type=hg:Place and thus gets both the place and the municipality?

**Comment by phpetra** [comment]
Can not reproduce. Think I accidentally fixed this ;-)
