### ISSUE TITLE
Unclosed a tag on 'meerdere resultaten'?

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#66]
From the second item on, links appear where they shouldn't:

![image](https://cloud.githubusercontent.com/assets/4539618/10783754/50656544-7d5a-11e5-96a9-c60772f8dd3e.png)

There seems to be an unneeded a tag outside the li?

**Comment by phpetra** [comment]
@mmmenno Can't you fix that?
