### ISSUE TITLE
"Oops sorry, but something went wrong" /  "er is iets mis"

### ISSUE THREAD

**Issue by jobspierings** [erfgoed-en-locatie/place-identificator#69]
#### test

CSV bestand met 100 regels, instellingen in stap 2: `hg:Municipality` naar `bag` met `geometrie`.

bewaar en test leidt tot leeg scherm met:

> Oops sorry, but something went wrong.

`backspace` en bewaar instellingen:

> De instellingen zijn aangepast en opgeslagen.

standaardiseer leidt tot

> De standaardisatie is begonnen! U krijgt een mail als het proces klaar is.
> Sorry, maar er is iets mis met de Histograph API. Probeer het svp wat later nog eens.

echter http://histograph.io/viewer/#search=%22Mill%20en%20Sint-Hubert%22 werkt gewoon. Email komt niet.
#### check csv bestand

M'n csv bestand heeft spatie tussen `;` en `toponiem`. Daarom versie gemaakt zonder _die_ spaties. Resultaten gelijk.
##### browser

OSx / Chrome `46.0.2490.86 (Officiële build) (64-bits)`

**Comment by phpetra** [comment]
Job,

ik denk dat je een paar stappen vergeten bent:
In de database staat nergens wat je "scheidingsteken" is, dat moet je nu zelf opgeven, anders gaat het mis. 
Wil je eens naar het configuratiescherm (de ornaje knop in het overzicht) gaan en daar die puntkomma invoeren?

En daarna - voor de zekerheid - eerst: "maak leeg" en daarna opnieuw standaardiseren?

**Comment by phpetra** [comment]
Job: ik zit net even je csv-bestand te debuggen maar dat is gewoon een gek ding en daar ligt het aan;
rare windows regel-eindes waarmee de csv-lezer vooralsnog niet kan omgaan en tekst die niet enclosed wordt door "-tekens (of iets anders).
Ik heb je bestand omgezet en zal het je zo even mailen, dan kun je het iig opnieuw proberen

**Comment by jobspierings** [comment]
ok - opgelost, issue is met type csv bestand, niet met de applicatie.

voor csv issue zie: http://nicercode.github.io/blog/2013-04-30-excel-and-line-endings/
