### ISSUE TITLE
tool: keuzemogelijkheid bij meerdere resultaten

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/place-identificator#8]
Als er meerdere mogelijkheden zijn gevonden, dan moet de gebruiker kunnen aangeven welke plaats het volgens hem / haar betreft ('geen idee' mag ook). Dit zal het makkelijkst gaan wanneer de mogelijkheden op een kaartje weergegeven worden.

**Comment by phpetra** [comment]
Het opslaan werkt nu via API call maar de aantallen in de tabjes moeten nog aangepast worden en er moet iets verzonnen worden waar we de gebruiker vervolgens heen kunnen sturen...?

Ooh, en de verschillende API's zijn stuk.... dus ik heb weer een /web/api-dummy.json gemaakt (Afferden)
